import { useDeferredValue, useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, ClipboardList, Copy, FileSpreadsheet, Filter, KeyRound, Mail, MapPin, Phone, Search, Trash2, UserPlus, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api, ApiError } from '../api'
import type { AuditLog, CurrentUser, HallRole, PagedResult, ProvisionedAccount, ResidentAssistant, Schedule, TemporaryPassword } from '../types'
import { Dialog, EmptyState, ErrorState } from '../components/ui'
import { useToast } from '../components/toast'
import { addScheduleMonths, compareSchedulePeriods, currentSchedulePeriod, monthName, type SchedulePeriod } from '../scheduleFormat'

export function AdminDashboardPage() {
  const currentPeriod = currentSchedulePeriod(); const latestPeriod = addScheduleMonths(currentPeriod, 2)
  const [period, setPeriod] = useState(currentPeriod); const [search, setSearch] = useState('')
  const deferredSearch = useDeferredValue(search)
  const queryClient = useQueryClient(); const toast = useToast()
  const schedule = useQuery({ queryKey: ['schedule', period.year, period.month], queryFn: ({ signal }) => api<Schedule>(`/api/schedules/${period.year}/${period.month}`, {}, signal) })
  const generate = useMutation({ mutationFn: () => api<Schedule>(`/api/admin/schedules/${period.year}/${period.month}/generate`, { method: 'POST', body: JSON.stringify({}) }), onSuccess: async () => { toast('Monthly shifts are live.'); await queryClient.invalidateQueries({ queryKey: ['schedule', period.year, period.month] }) } })
  const people = useQuery({ queryKey: ['admin', 'users'], queryFn: ({ signal }) => api<ResidentAssistant[]>('/api/admin/users', {}, signal) })
  const canGoBack = compareSchedulePeriods(period, currentPeriod) > 0
  const canGoForward = compareSchedulePeriods(period, latestPeriod) < 0
  const changeMonth = (offset: number) => setPeriod(addScheduleMonths(period, offset))
  const missingSchedule = schedule.error instanceof ApiError && schedule.error.problem.code === 'SCHEDULE_NOT_FOUND'
  const ras = people.data?.filter((person) => person.role === 'ResidentAssistant') ?? []
  const visibleRas = ras.filter((ra) => `${ra.firstName} ${ra.lastName} ${ra.schoolEmail} ${ra.roomNumber ?? ''}`.toLowerCase().includes(deferredSearch.toLowerCase()))
  return <div className="page page--narrow manage-page">
    <div className="page-heading people-heading"><div><span className="eyebrow">Hall management</span><h1>Resident Assistants</h1><p>Manage the Eltse Hall team and their contact information.</p></div><div className="manage-heading-actions"><Link className="button button--primary" to="/admin/users"><UsersRound size={17} />Manage RAs</Link><Link className="button button--quiet" to="/admin/residents"><FileSpreadsheet size={17} />Import residents</Link><Link className="button button--quiet" to="/admin/audit"><ClipboardList size={17} />Activity</Link></div></div>

    <section className="manage-schedule-row" aria-label="Schedule setup">
      <div className="manage-schedule-copy">{schedule.data ? <CheckCircle2 /> : <CalendarDays />}<span><strong>{monthName(period.month)} schedule</strong><small>{schedule.isLoading ? 'Checking schedule…' : schedule.data ? `${schedule.data.shifts.length} nights ready` : missingSchedule ? 'Not started' : 'Unavailable'}</small></span></div>
      <MonthWindowPicker period={period} canGoBack={canGoBack} canGoForward={canGoForward} onChange={changeMonth} />
      {missingSchedule && <button className="button button--primary" onClick={() => generate.mutate()} disabled={generate.isPending}>{generate.isPending ? 'Starting…' : 'Start schedule'}</button>}
      {schedule.data && <Link className="button button--quiet" to="/schedule">Open schedule</Link>}
      {schedule.isError && !missingSchedule && <button className="button button--quiet" onClick={() => schedule.refetch()}>Try again</button>}
    </section>
    {generate.isError && <p className="inline-error" role="alert">{generate.error instanceof ApiError ? generate.error.problem.title : 'The schedule could not be started.'}</p>}

    <div className="directory-toolbar"><label className="search-field"><Search size={18} /><span className="sr-only">Search resident assistants</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name or room" /></label><span>{visibleRas.length} RAs</span></div>
    {people.isLoading && <div className="table-skeleton">{Array.from({ length: 5 }, (_, index) => <div className="skeleton skeleton--row" key={index} />)}</div>}
    {people.isError && <ErrorState title="RA directory unavailable" message="The staff list could not be loaded." onRetry={() => people.refetch()} />}
    {people.data && !visibleRas.length && <EmptyState title={search ? 'No matching RAs' : 'No resident assistants yet'} message={search ? 'Try a different name or room number.' : 'Add an RA account to start building the hall team.'} />}
    {!!visibleRas.length && <div className="responsive-table manage-ra-table"><table><caption className="sr-only">Resident assistant management directory</caption><thead><tr><th>Name</th><th>Room</th><th>Phone</th><th>Email</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{visibleRas.map((ra) => <tr key={ra.id} className={!ra.isActive ? 'row-inactive' : ''}><td data-label="Name"><span className="person-cell"><span className="avatar">{ra.firstName[0]}{ra.lastName[0]}</span><strong>{ra.firstName} {ra.lastName}</strong></span></td><td data-label="Room"><span className="with-icon"><MapPin size={15} />{ra.roomNumber ?? 'Not listed'}</span></td><td data-label="Phone">{ra.phoneNumber ? <a className="with-icon" href={`tel:${ra.phoneNumber}`}><Phone size={15} />{ra.phoneNumber}</a> : 'Not listed'}</td><td data-label="Email"><a className="with-icon" href={`mailto:${ra.schoolEmail}`}><Mail size={15} />{ra.schoolEmail}</a></td><td data-label="Status"><span className={`active-state ${ra.isActive ? 'is-active' : ''}`}>{ra.isActive ? 'Active' : 'Inactive'}</span></td><td data-label="Actions"><Link className="text-link" to="/admin/users">Edit</Link></td></tr>)}</tbody></table></div>}
  </div>
}

function MonthWindowPicker({ period, canGoBack, canGoForward, onChange }: { period: SchedulePeriod; canGoBack: boolean; canGoForward: boolean; onChange: (offset: number) => void }) {
  return <div className="admin-month-picker" aria-label="Schedule month"><button type="button" onClick={() => onChange(-1)} disabled={!canGoBack} aria-label="Previous month"><ChevronLeft size={18} /></button><span><strong>{monthName(period.month)}</strong><small>{period.year}</small></span><button type="button" onClick={() => onChange(1)} disabled={!canGoForward} aria-label="Next month"><ChevronRight size={18} /></button></div>
}

export function UserManagementPage({ currentUser }: { currentUser: CurrentUser }) {
  const [search, setSearch] = useState(''); const [editing, setEditing] = useState<ResidentAssistant | null>(null)
  const [creating, setCreating] = useState(false); const [credential, setCredential] = useState<{ email: string; password: string } | null>(null)
  const users = useQuery({ queryKey: ['admin', 'users'], queryFn: ({ signal }) => api<ResidentAssistant[]>('/api/admin/users', {}, signal) })
  const visible = users.data?.filter((user) => `${user.firstName} ${user.lastName} ${user.schoolEmail} ${user.roomNumber ?? ''}`.toLowerCase().includes(search.toLowerCase()))
  return <div className="page page--narrow"><div className="page-heading people-heading"><div><span className="eyebrow">Account administration</span><h1>People</h1><p>Create approved accounts, manage roles, and control access.</p></div><button className="button button--primary" onClick={() => setCreating(true)}><UserPlus size={17} />Add person</button></div><div className="directory-toolbar"><label className="search-field"><Search size={18} /><span className="sr-only">Search people</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search people" /></label><div className="filter-label"><Filter size={16} />Active and inactive</div></div>
    {users.isError && <ErrorState message="People could not be loaded." />}{visible && <div className="responsive-table"><table><thead><tr><th>Name</th><th>Status</th><th>Role</th><th>Room</th><th>Phone</th><th>Current shifts</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{visible.map((user) => <tr key={user.id} className={!user.isActive ? 'row-inactive' : ''}><td data-label="Name"><span className="person-cell"><span className="avatar">{user.firstName[0]}{user.lastName[0]}</span><span><strong>{user.firstName} {user.lastName}</strong><small>{user.schoolEmail}</small></span></span></td><td data-label="Status"><span className={`active-state ${user.isActive ? 'is-active' : ''}`}>{user.isActive ? 'Active' : 'Inactive'}</span></td><td data-label="Role">{roleLabel(user.role)}</td><td data-label="Room">{user.roomNumber ?? '—'}</td><td data-label="Phone">{user.phoneNumber ?? '—'}</td><td data-label="Current shifts">{user.shiftCount}</td><td><button className="text-button" onClick={() => setEditing(user)}>Edit</button></td></tr>)}</tbody></table></div>}
    <CreateUserDialog open={creating} currentUser={currentUser} onClose={() => setCreating(false)} onProvisioned={(email, password) => { setCreating(false); setCredential({ email, password }) }} />
    <EditUserDialog user={editing} currentUser={currentUser} onClose={() => setEditing(null)} onPasswordReset={(email, password) => { setEditing(null); setCredential({ email, password }) }} />
    <TemporaryPasswordDialog credential={credential} onClose={() => setCredential(null)} /></div>
}

function CreateUserDialog({ open, currentUser, onClose, onProvisioned }: { open: boolean; currentUser: CurrentUser; onClose: () => void; onProvisioned: (email: string, password: string) => void }) {
  const queryClient = useQueryClient(); const [form, setForm] = useState({ email: '', firstName: '', lastName: '', role: 'ResidentAssistant' as HallRole, roomNumber: '', phoneNumber: '' })
  const mutation = useMutation({ mutationFn: () => api<ProvisionedAccount>('/api/admin/users', { method: 'POST', body: JSON.stringify(form) }), onSuccess: async (result) => { onProvisioned(result.user.schoolEmail, result.temporaryPassword); setForm({ email: '', firstName: '', lastName: '', role: 'ResidentAssistant', roomNumber: '', phoneNumber: '' }); await queryClient.invalidateQueries({ queryKey: ['admin', 'users'] }) } })
  return <Dialog open={open} onClose={onClose} title="Add Residence Life account"><form className="dialog-form account-form" onSubmit={(event) => { event.preventDefault(); mutation.mutate() }}><label className="field"><span>School email</span><input type="email" autoComplete="off" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="name@wmpenn.edu" required /></label><div className="form-grid"><label className="field"><span>First name</span><input value={form.firstName} onChange={(event) => setForm({ ...form, firstName: event.target.value })} required /></label><label className="field"><span>Last name</span><input value={form.lastName} onChange={(event) => setForm({ ...form, lastName: event.target.value })} required /></label></div><label className="field"><span>Role</span><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as HallRole })}>{roleOptions(currentUser.role).map((role) => <option value={role} key={role}>{roleLabel(role)}</option>)}</select></label><div className="form-grid"><label className="field"><span>Room number</span><input value={form.roomNumber} onChange={(event) => setForm({ ...form, roomNumber: event.target.value })} /></label><label className="field"><span>Phone number</span><input type="tel" value={form.phoneNumber} onChange={(event) => setForm({ ...form, phoneNumber: event.target.value })} /></label></div><p className="form-note">A temporary password will be shown once. Give it to this person through a private channel.</p>{mutation.isError && <p className="inline-error" role="alert">{mutation.error instanceof ApiError ? mutation.error.problem.title : 'Account creation failed.'}</p>}<div className="dialog-actions"><button className="button button--primary" disabled={mutation.isPending}>{mutation.isPending ? 'Creating…' : 'Create account'}</button><button className="button button--quiet" type="button" onClick={onClose}>Cancel</button></div></form></Dialog>
}

function EditUserDialog({ user, currentUser, onClose, onPasswordReset }: { user: ResidentAssistant | null; currentUser: CurrentUser; onClose: () => void; onPasswordReset: (email: string, password: string) => void }) {
  const queryClient = useQueryClient(); const toast = useToast(); const [confirmDelete, setConfirmDelete] = useState(false)
  const [form, setForm] = useState({ roomNumber: '', phoneNumber: '', role: 'ResidentAssistant' as HallRole, isActive: true })
  useEffect(() => { if (user) { setForm({ roomNumber: user.roomNumber ?? '', phoneNumber: user.phoneNumber ?? '', role: user.role, isActive: user.isActive }); setConfirmDelete(false) } }, [user])
  const mutation = useMutation({ mutationFn: () => api(`/api/admin/users/${user?.id}`, { method: 'PUT', body: JSON.stringify(form) }), onSuccess: async () => { toast('User record updated.'); onClose(); await queryClient.invalidateQueries({ queryKey: ['admin', 'users'] }) } })
  const reset = useMutation({ mutationFn: () => api<TemporaryPassword>(`/api/admin/users/${user?.id}/reset-password`, { method: 'POST' }), onSuccess: (result) => { if (user) onPasswordReset(user.schoolEmail, result.temporaryPassword) } })
  const remove = useMutation({ mutationFn: () => api(`/api/admin/users/${user?.id}`, { method: 'DELETE' }), onSuccess: async () => { toast('Person deleted.'); onClose(); await queryClient.invalidateQueries({ queryKey: ['admin', 'users'] }) } })
  const isSelf = user?.id === currentUser.id
  const canDelete = !!user && !isSelf && (currentUser.role === 'Admin' || user.role === 'ResidentAssistant')
  return <Dialog open={!!user} onClose={onClose} title={user ? `Edit ${user.firstName} ${user.lastName}` : 'Edit user'}><form className="dialog-form" onSubmit={(event) => { event.preventDefault(); mutation.mutate() }}><label className="field"><span>School email</span><input value={user?.schoolEmail ?? ''} disabled /></label><label className="field"><span>Room number</span><input value={form.roomNumber} onChange={(event) => setForm({ ...form, roomNumber: event.target.value })} /></label><label className="field"><span>Phone number</span><input value={form.phoneNumber} onChange={(event) => setForm({ ...form, phoneNumber: event.target.value })} /></label><label className="field"><span>Role</span><select value={form.role} disabled={currentUser.role !== 'Admin' || isSelf} onChange={(event) => setForm({ ...form, role: event.target.value as HallRole })}>{roleOptions(currentUser.role).map((role) => <option value={role} key={role}>{roleLabel(role)}</option>)}</select></label><label className="checkbox-field"><input type="checkbox" checked={form.isActive} disabled={isSelf} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} /><span><strong>Active in this hall</strong><small>Deactivation ends access and scheduling eligibility.</small></span></label>{(mutation.isError || reset.isError || remove.isError) && <p className="inline-error" role="alert">{mutation.error instanceof ApiError ? mutation.error.problem.title : reset.error instanceof ApiError ? reset.error.problem.title : remove.error instanceof ApiError ? remove.error.problem.title : 'The account change failed.'}</p>}<div className="dialog-actions"><button className="button button--primary" type="submit" disabled={mutation.isPending || remove.isPending}>Save changes</button><button className="button button--quiet" type="button" onClick={() => reset.mutate()} disabled={reset.isPending || remove.isPending || isSelf}><KeyRound size={16} />{reset.isPending ? 'Resetting…' : 'Reset password'}</button><button className={confirmDelete ? 'button button--danger' : 'button button--danger-quiet'} type="button" onClick={() => confirmDelete ? remove.mutate() : setConfirmDelete(true)} disabled={!canDelete || remove.isPending}><Trash2 size={16} />{remove.isPending ? 'Deleting...' : confirmDelete ? 'Confirm delete' : 'Delete person'}</button><button className="button button--quiet" type="button" onClick={onClose} disabled={remove.isPending}>Cancel</button></div></form></Dialog>
}

function TemporaryPasswordDialog({ credential, onClose }: { credential: { email: string; password: string } | null; onClose: () => void }) {
  const [copied, setCopied] = useState(false)
  useEffect(() => { setCopied(false) }, [credential])
  return <Dialog open={!!credential} onClose={onClose} title="Temporary password"><div className="temporary-credential"><KeyRound /><p>Share this temporary password with the new user.</p><strong>{credential?.email}</strong><code>{credential?.password}</code><button className="button button--primary" onClick={async () => { if (credential) { await navigator.clipboard.writeText(credential.password); setCopied(true) } }}><Copy size={16} />{copied ? 'Copied' : 'Copy password'}</button><small>The user must replace it with a private 15-character-or-longer password at first sign-in.</small></div><div className="dialog-actions"><button className="button button--quiet" onClick={onClose}>Done</button></div></Dialog>
}

export function AuditLogPage() {
  const [page, setPage] = useState(1); const [filter, setFilter] = useState('')
  const audit = useQuery({ queryKey: ['audit', page, filter], queryFn: ({ signal }) => api<PagedResult<AuditLog>>(`/api/admin/audit-logs?page=${page}&pageSize=20${filter ? `&action=${encodeURIComponent(filter)}` : ''}`, {}, signal) })
  return <div className="page page--narrow"><div className="page-heading"><div><span className="eyebrow">Accountability</span><h1>Audit history</h1><p>Important administrative changes across this residence hall.</p></div></div><div className="directory-toolbar"><label className="search-field"><Search size={18} /><span className="sr-only">Filter by action</span><input value={filter} onChange={(event) => { setFilter(event.target.value); setPage(1) }} placeholder="Filter by action" /></label><span>{audit.data?.total ?? 0} events</span></div>
    {audit.isError && <ErrorState message="Audit history could not be loaded." />}{audit.data && !audit.data.items.length && <EmptyState title="No activity found" message="Try a broader action filter." />}{audit.data?.items.length ? <div className="audit-table responsive-table"><table><thead><tr><th>Date and time</th><th>Actor</th><th>Action</th><th>Affected record</th><th>Change summary</th></tr></thead><tbody>{audit.data.items.map((item) => <tr key={item.id}><td data-label="Date"><time>{new Date(item.occurredAt).toLocaleString()}</time></td><td data-label="Actor"><strong>{item.actor}</strong></td><td data-label="Action">{readableAction(item.action)}</td><td data-label="Record"><span>{item.entityType}</span><small>{item.entityId.slice(0, 8)}…</small></td><td data-label="Summary"><details><summary>Before and after</summary><pre>{summaryJson(item.before, item.after)}</pre></details></td></tr>)}</tbody></table><div className="pagination"><button className="button button--quiet" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Page {page} of {Math.max(1, Math.ceil(audit.data.total / audit.data.pageSize))}</span><button className="button button--quiet" disabled={page * audit.data.pageSize >= audit.data.total} onClick={() => setPage((value) => value + 1)}>Next</button></div></div> : null}</div>
}

function readableAction(action: string) { return action.toLowerCase().replaceAll('_', ' ') }
function summaryJson(before?: string, after?: string) { try { return `Before\n${before ? JSON.stringify(JSON.parse(before), null, 2) : '—'}\n\nAfter\n${after ? JSON.stringify(JSON.parse(after), null, 2) : '—'}` } catch { return 'Change details unavailable.' } }
function roleLabel(role: 'ResidentAssistant' | 'HallDirector' | 'Admin') { return role === 'Admin' ? 'Administrator' : role === 'HallDirector' ? 'Hall Director' : 'Resident Assistant' }
function roleOptions(actorRole: HallRole): HallRole[] { return actorRole === 'Admin' ? ['ResidentAssistant', 'HallDirector', 'Admin'] : ['ResidentAssistant'] }
