import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, Archive, ArrowDown, ArrowUp, CheckCircle2, Copy, Filter, KeyRound, Search, Send, UserPlus } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api, ApiError } from '../api'
import type { AuditLog, CurrentUser, Distribution, HallRole, PagedResult, ProvisionedAccount, ResidentAssistant, Schedule, ScheduleStatus, Shift, TemporaryPassword } from '../types'
import { Dialog, EmptyState, ErrorState } from '../components/ui'
import { useToast } from '../components/toast'
import { monthName } from '../scheduleFormat'

export function AdminDashboardPage() {
  const today = new Date(); const year = today.getFullYear(); const month = today.getMonth() + 1
  const queryClient = useQueryClient(); const toast = useToast(); const [confirm, setConfirm] = useState<ScheduleStatus | null>(null)
  const schedule = useQuery({ queryKey: ['schedule', year, month], queryFn: ({ signal }) => api<Schedule>(`/api/schedules/${year}/${month}`, {}, signal) })
  const generate = useMutation({ mutationFn: () => api<Schedule>(`/api/admin/schedules/${year}/${month}/generate`, { method: 'POST', body: JSON.stringify({}) }), onSuccess: async () => { toast('Monthly shifts generated.'); await queryClient.invalidateQueries({ queryKey: ['schedule'] }) } })
  const unfilled = useQuery({ queryKey: ['admin', 'unfilled', schedule.data?.id], queryFn: ({ signal }) => api<Shift[]>(`/api/admin/schedules/${schedule.data?.id}/unfilled`, {}, signal), enabled: !!schedule.data })
  const distribution = useQuery({ queryKey: ['admin', 'distribution', schedule.data?.id], queryFn: ({ signal }) => api<Distribution[]>(`/api/admin/schedules/${schedule.data?.id}/distribution`, {}, signal), enabled: !!schedule.data })
  const activity = useQuery({ queryKey: ['admin', 'audit', 1], queryFn: ({ signal }) => api<PagedResult<AuditLog>>('/api/admin/audit-logs?page=1&pageSize=6', {}, signal) })
  const transition = useMutation({ mutationFn: (status: ScheduleStatus) => api<Schedule>(`/api/admin/schedules/${schedule.data?.id}/${routeFor(status)}`, { method: 'POST' }), onSuccess: async (_, status) => { toast(`Schedule ${pastTense(status)}.`); setConfirm(null); await queryClient.invalidateQueries({ queryKey: ['schedule'] }) } })
  if (schedule.isLoading) return <div className="page"><div className="skeleton skeleton--title" /><div className="admin-skeleton"><div className="skeleton" /><div className="skeleton" /></div></div>
  if (schedule.isError) {
    const missing = schedule.error instanceof ApiError && schedule.error.problem.code === 'SCHEDULE_NOT_FOUND'
    return <div className="page"><div className="page-heading"><div><span className="eyebrow">Hall Director desk</span><h1>{monthName(month)} schedule operations</h1></div></div>{missing ? <div className="state-message"><div><h2>No schedule exists for this month</h2><p>Generate one night-duty shift for each date using the standard hall configuration.</p><button className="button button--primary" onClick={() => generate.mutate()} disabled={generate.isPending}>{generate.isPending ? 'Generating…' : 'Generate monthly shifts'}</button></div></div> : <ErrorState title="Director desk unavailable" message={schedule.error instanceof ApiError ? schedule.error.problem.title : 'The current schedule could not be loaded.'} />}</div>
  }
  if (!schedule.data) return null
  const below = distribution.data?.filter((x) => x.balance === 'Below target') ?? []
  const atLimit = distribution.data?.filter((x) => x.balance === 'At limit') ?? []
  const nextActions = validActions(schedule.data.status)
  return <div className="page page--admin">
    <div className="page-heading admin-heading"><div><span className="eyebrow">Hall Director desk</span><h1>{monthName(month)} schedule operations</h1><p>{schedule.data.residenceHallName} · Review coverage before publishing.</p></div><span className={`large-status large-status--${schedule.data.status}`}>{humanStatus(schedule.data.status)}</span></div>
    <div className="admin-command-bar"><div><strong>Schedule lifecycle</strong><span>{lifecycleHelp(schedule.data.status)}</span></div><div>{nextActions.map((status) => <button key={status} className={status === 'Published' ? 'button button--primary' : 'button button--quiet'} onClick={() => status === 'Published' || status === 'Archived' ? setConfirm(status) : transition.mutate(status)} disabled={transition.isPending}>{iconFor(status)}{actionLabel(status)}</button>)}</div></div>
    {transition.isError && <p className="inline-error" role="alert">{transition.error instanceof ApiError ? transition.error.problem.title : 'The schedule state could not be changed.'}</p>}
    <div className="decision-strip"><DecisionMetric value={unfilled.data?.length ?? '—'} label="Unfilled nights" tone={unfilled.data?.length ? 'danger' : 'good'} detail={unfilled.data?.length ? 'Needs attention' : 'Coverage complete'} /><DecisionMetric value={below.length} label="RAs below target" tone={below.length ? 'warning' : 'good'} detail="Balance before publish" /><DecisionMetric value={atLimit.length} label="RAs at limit" detail={`Max ${schedule.data.configuration.maximumShiftsPerUser} shifts`} /><DecisionMetric value={distribution.data?.reduce((sum, row) => sum + row.weekendShifts, 0) ?? '—'} label="Weekend assignments" detail="Friday and Saturday" /></div>
    <div className="admin-grid"><section className="admin-section distribution-section"><div className="section-heading"><div><span className="eyebrow">Coverage balance</span><h2>Assignment distribution</h2></div><a href="/admin/users" className="text-link">Manage people</a></div>
      {distribution.data?.length ? <div className="distribution-list">{distribution.data.map((row) => <div className="distribution-row" key={row.userId}><span className="avatar">{initials(row.name)}</span><strong>{row.name}</strong><span className={`balance balance--${row.balance.replace(' ', '-').toLowerCase()}`}>{row.balance === 'Below target' ? <ArrowDown size={14} /> : row.balance === 'At limit' ? <ArrowUp size={14} /> : <CheckCircle2 size={14} />}{row.balance}</span><span><b>{row.totalShifts}</b> total</span><span><b>{row.weekendShifts}</b> weekend</span></div>)}</div> : <EmptyState title="No active RAs" message="Activate resident assistants before assigning coverage." />}</section>
      <aside className="admin-section attention-section"><div className="section-heading"><div><span className="eyebrow">Priority queue</span><h2>Unfilled nights</h2></div><span>{unfilled.data?.length ?? 0}</span></div>{unfilled.data?.length ? <ol>{unfilled.data.slice(0, 8).map((shift) => <li key={shift.id}><time>{new Date(`${shift.dutyDate}T12:00:00`).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })}</time><span>{shift.requiredStaffCount - shift.assignments.length} opening</span></li>)}</ol> : <div className="coverage-complete"><CheckCircle2 /><strong>Every night is covered</strong><p>No staffing gaps remain this month.</p></div>}</aside>
    </div>
    <section className="activity-section"><div className="section-heading"><div><span className="eyebrow">Accountability</span><h2>Recent administrative activity</h2></div><Link to="/admin/audit" className="text-link">View full history</Link></div><div className="activity-list">{activity.data?.items.map((item) => <div key={item.id}><span className="activity-dot" /><time>{new Date(item.occurredAt).toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</time><p><strong>{item.actor}</strong> {readableAction(item.action)}</p><small>{item.entityType}</small></div>)}</div></section>
    <Dialog open={!!confirm} onClose={() => setConfirm(null)} title={confirm === 'Published' ? 'Publish this schedule?' : 'Archive this schedule?'}><div className="confirm-dialog"><AlertTriangle /><p>{confirm === 'Published' ? 'Publishing makes this the final downloadable schedule for all authorized staff. You can return it to Closed if corrections are needed.' : 'Archiving is final and retains the schedule only for historical reference.'}</p><div className="dialog-actions"><button className="button button--primary" onClick={() => confirm && transition.mutate(confirm)} disabled={transition.isPending}>{transition.isPending ? 'Working…' : confirm === 'Published' ? 'Publish schedule' : 'Archive schedule'}</button><button className="button button--quiet" onClick={() => setConfirm(null)}>Cancel</button></div></div></Dialog>
  </div>
}

export function UserManagementPage({ currentUser }: { currentUser: CurrentUser }) {
  const [search, setSearch] = useState(''); const [editing, setEditing] = useState<ResidentAssistant | null>(null)
  const [creating, setCreating] = useState(false); const [credential, setCredential] = useState<{ email: string; password: string } | null>(null)
  const users = useQuery({ queryKey: ['admin', 'users'], queryFn: ({ signal }) => api<ResidentAssistant[]>('/api/admin/users', {}, signal) })
  const visible = users.data?.filter((user) => `${user.firstName} ${user.lastName} ${user.schoolEmail} ${user.roomNumber ?? ''}`.toLowerCase().includes(search.toLowerCase()))
  return <div className="page page--narrow"><div className="page-heading people-heading"><div><span className="eyebrow">Account administration</span><h1>People</h1><p>Create approved accounts, manage roles, and control access.</p></div><button className="button button--primary" onClick={() => setCreating(true)}><UserPlus size={17} />Add person</button></div><div className="directory-toolbar"><label className="search-field"><Search size={18} /><span className="sr-only">Search people</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search people" /></label><div className="filter-label"><Filter size={16} />Active and inactive</div></div>
    {users.isError && <ErrorState message="People could not be loaded." />}{visible && <div className="responsive-table"><table><thead><tr><th>Name</th><th>Status</th><th>Role</th><th>Room</th><th>Phone</th><th>Current shifts</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{visible.map((user) => <tr key={user.id} className={!user.isActive ? 'row-inactive' : ''}><td data-label="Name"><span className="person-cell"><span className="avatar">{user.firstName[0]}{user.lastName[0]}</span><span><strong>{user.firstName} {user.lastName}</strong><small>{user.schoolEmail}</small></span></span></td><td data-label="Status"><span className={`active-state ${user.isActive ? 'is-active' : ''}`}>{user.isActive ? 'Active' : 'Inactive'}</span></td><td data-label="Role">{roleLabel(user.role)}</td><td data-label="Room">{user.roomNumber ?? '—'}</td><td data-label="Phone">{user.phoneNumber ?? '—'}</td><td data-label="Current shifts">{user.shiftCount}</td><td><button className="text-button" onClick={() => setEditing(user)}>Edit</button></td></tr>)}</tbody></table></div>}
    <CreateUserDialog open={creating} currentUser={currentUser} onClose={() => setCreating(false)} onProvisioned={(email, password) => { setCreating(false); setCredential({ email, password }) }} />
    <EditUserDialog user={editing} currentUser={currentUser} onClose={() => setEditing(null)} onPasswordReset={(email, password) => { setEditing(null); setCredential({ email, password }) }} />
    <TemporaryPasswordDialog credential={credential} onClose={() => setCredential(null)} /></div>
}

function CreateUserDialog({ open, currentUser, onClose, onProvisioned }: { open: boolean; currentUser: CurrentUser; onClose: () => void; onProvisioned: (email: string, password: string) => void }) {
  const queryClient = useQueryClient(); const [form, setForm] = useState({ email: '', firstName: '', lastName: '', role: 'ResidentAssistant' as HallRole, roomNumber: '', phoneNumber: '' })
  const mutation = useMutation({ mutationFn: () => api<ProvisionedAccount>('/api/admin/users', { method: 'POST', body: JSON.stringify(form) }), onSuccess: async (result) => { onProvisioned(result.user.schoolEmail, result.temporaryPassword); setForm({ email: '', firstName: '', lastName: '', role: 'ResidentAssistant', roomNumber: '', phoneNumber: '' }); await queryClient.invalidateQueries({ queryKey: ['admin', 'users'] }) } })
  return <Dialog open={open} onClose={onClose} title="Add Residence Life account"><form className="dialog-form account-form" onSubmit={(event) => { event.preventDefault(); mutation.mutate() }}><label className="field"><span>School email</span><input type="email" autoComplete="off" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="name@wmpenn.edu" required /></label><div className="form-grid"><label className="field"><span>First name</span><input value={form.firstName} onChange={(event) => setForm({ ...form, firstName: event.target.value })} required /></label><label className="field"><span>Last name</span><input value={form.lastName} onChange={(event) => setForm({ ...form, lastName: event.target.value })} required /></label></div><label className="field"><span>Role</span><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as HallRole })}>{roleOptions(currentUser.role).map((role) => <option value={role} key={role}>{roleLabel(role)}</option>)}</select></label><div className="form-grid"><label className="field"><span>Room number</span><input value={form.roomNumber} onChange={(event) => setForm({ ...form, roomNumber: event.target.value })} /></label><label className="field"><span>Phone number</span><input type="tel" value={form.phoneNumber} onChange={(event) => setForm({ ...form, phoneNumber: event.target.value })} /></label></div><p className="form-note">A temporary password will be shown once. Give it to this person through a private channel.</p>{mutation.isError && <p className="inline-error" role="alert">{mutation.error instanceof ApiError ? mutation.error.problem.title : 'Account creation failed.'}</p>}<div className="dialog-actions"><button className="button button--primary" disabled={mutation.isPending}>{mutation.isPending ? 'Creating…' : 'Create account'}</button><button className="button button--quiet" type="button" onClick={onClose}>Cancel</button></div></form></Dialog>
}

function EditUserDialog({ user, currentUser, onClose, onPasswordReset }: { user: ResidentAssistant | null; currentUser: CurrentUser; onClose: () => void; onPasswordReset: (email: string, password: string) => void }) {
  const queryClient = useQueryClient(); const toast = useToast(); const [form, setForm] = useState({ roomNumber: '', phoneNumber: '', role: 'ResidentAssistant' as HallRole, isActive: true })
  useEffect(() => { if (user) setForm({ roomNumber: user.roomNumber ?? '', phoneNumber: user.phoneNumber ?? '', role: user.role, isActive: user.isActive }) }, [user])
  const mutation = useMutation({ mutationFn: () => api(`/api/admin/users/${user?.id}`, { method: 'PUT', body: JSON.stringify(form) }), onSuccess: async () => { toast('User record updated.'); onClose(); await queryClient.invalidateQueries({ queryKey: ['admin', 'users'] }) } })
  const reset = useMutation({ mutationFn: () => api<TemporaryPassword>(`/api/admin/users/${user?.id}/reset-password`, { method: 'POST' }), onSuccess: (result) => { if (user) onPasswordReset(user.schoolEmail, result.temporaryPassword) } })
  const isSelf = user?.id === currentUser.id
  return <Dialog open={!!user} onClose={onClose} title={user ? `Edit ${user.firstName} ${user.lastName}` : 'Edit user'}><form className="dialog-form" onSubmit={(event) => { event.preventDefault(); mutation.mutate() }}><label className="field"><span>School email</span><input value={user?.schoolEmail ?? ''} disabled /></label><label className="field"><span>Room number</span><input value={form.roomNumber} onChange={(event) => setForm({ ...form, roomNumber: event.target.value })} /></label><label className="field"><span>Phone number</span><input value={form.phoneNumber} onChange={(event) => setForm({ ...form, phoneNumber: event.target.value })} /></label><label className="field"><span>Role</span><select value={form.role} disabled={currentUser.role !== 'Admin' || isSelf} onChange={(event) => setForm({ ...form, role: event.target.value as HallRole })}>{roleOptions(currentUser.role).map((role) => <option value={role} key={role}>{roleLabel(role)}</option>)}</select></label><label className="checkbox-field"><input type="checkbox" checked={form.isActive} disabled={isSelf} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} /><span><strong>Active in this hall</strong><small>Deactivation ends access and scheduling eligibility.</small></span></label>{(mutation.isError || reset.isError) && <p className="inline-error" role="alert">{mutation.error instanceof ApiError ? mutation.error.problem.title : reset.error instanceof ApiError ? reset.error.problem.title : 'The account change failed.'}</p>}<div className="dialog-actions"><button className="button button--primary" type="submit" disabled={mutation.isPending}>Save changes</button><button className="button button--quiet" type="button" onClick={() => reset.mutate()} disabled={reset.isPending || isSelf}><KeyRound size={16} />{reset.isPending ? 'Resetting…' : 'Reset password'}</button><button className="button button--quiet" type="button" onClick={onClose}>Cancel</button></div></form></Dialog>
}

function TemporaryPasswordDialog({ credential, onClose }: { credential: { email: string; password: string } | null; onClose: () => void }) {
  const [copied, setCopied] = useState(false)
  useEffect(() => { setCopied(false) }, [credential])
  return <Dialog open={!!credential} onClose={onClose} title="Temporary password"><div className="temporary-credential"><KeyRound /><p>Copy this password now. It will not be shown again.</p><strong>{credential?.email}</strong><code>{credential?.password}</code><button className="button button--primary" onClick={async () => { if (credential) { await navigator.clipboard.writeText(credential.password); setCopied(true) } }}><Copy size={16} />{copied ? 'Copied' : 'Copy password'}</button><small>The user must replace it with a private 15-character-or-longer password at first sign-in.</small></div><div className="dialog-actions"><button className="button button--quiet" onClick={onClose}>Done</button></div></Dialog>
}

export function AuditLogPage() {
  const [page, setPage] = useState(1); const [filter, setFilter] = useState('')
  const audit = useQuery({ queryKey: ['audit', page, filter], queryFn: ({ signal }) => api<PagedResult<AuditLog>>(`/api/admin/audit-logs?page=${page}&pageSize=20${filter ? `&action=${encodeURIComponent(filter)}` : ''}`, {}, signal) })
  return <div className="page page--narrow"><div className="page-heading"><div><span className="eyebrow">Accountability</span><h1>Audit history</h1><p>Important administrative changes across this residence hall.</p></div></div><div className="directory-toolbar"><label className="search-field"><Search size={18} /><span className="sr-only">Filter by action</span><input value={filter} onChange={(event) => { setFilter(event.target.value); setPage(1) }} placeholder="Filter by action" /></label><span>{audit.data?.total ?? 0} events</span></div>
    {audit.isError && <ErrorState message="Audit history could not be loaded." />}{audit.data && !audit.data.items.length && <EmptyState title="No activity found" message="Try a broader action filter." />}{audit.data?.items.length ? <div className="audit-table responsive-table"><table><thead><tr><th>Date and time</th><th>Actor</th><th>Action</th><th>Affected record</th><th>Change summary</th></tr></thead><tbody>{audit.data.items.map((item) => <tr key={item.id}><td data-label="Date"><time>{new Date(item.occurredAt).toLocaleString()}</time></td><td data-label="Actor"><strong>{item.actor}</strong></td><td data-label="Action">{readableAction(item.action)}</td><td data-label="Record"><span>{item.entityType}</span><small>{item.entityId.slice(0, 8)}…</small></td><td data-label="Summary"><details><summary>Before and after</summary><pre>{summaryJson(item.before, item.after)}</pre></details></td></tr>)}</tbody></table><div className="pagination"><button className="button button--quiet" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Page {page} of {Math.max(1, Math.ceil(audit.data.total / audit.data.pageSize))}</span><button className="button button--quiet" disabled={page * audit.data.pageSize >= audit.data.total} onClick={() => setPage((value) => value + 1)}>Next</button></div></div> : null}</div>
}

function DecisionMetric({ value, label, detail, tone = 'neutral' }: { value: string | number; label: string; detail: string; tone?: string }) { return <div className={`decision-metric decision-metric--${tone}`}><strong>{value}</strong><span>{label}<small>{detail}</small></span></div> }
function validActions(status: ScheduleStatus): ScheduleStatus[] { return ({ Draft: ['OpenForSelection'], OpenForSelection: ['Closed', 'Draft'], Closed: ['OpenForSelection', 'Published'], Published: ['Closed', 'Archived'], Archived: [] } as Record<ScheduleStatus, ScheduleStatus[]>)[status] }
function routeFor(status: ScheduleStatus) { return ({ OpenForSelection: 'open', Closed: 'close', Published: 'publish', Archived: 'archive', Draft: 'draft' } as Record<ScheduleStatus, string>)[status] }
function actionLabel(status: ScheduleStatus) { return ({ OpenForSelection: 'Open selection', Closed: 'Close selection', Published: 'Publish schedule', Archived: 'Archive', Draft: 'Return to draft' } as Record<ScheduleStatus, string>)[status] }
function iconFor(status: ScheduleStatus) { return status === 'Published' ? <Send size={16} /> : status === 'Archived' ? <Archive size={16} /> : undefined }
function pastTense(status: ScheduleStatus) { return ({ OpenForSelection: 'opened for selection', Closed: 'closed', Published: 'published', Archived: 'archived', Draft: 'returned to draft' } as Record<ScheduleStatus, string>)[status] }
function humanStatus(status: ScheduleStatus) { return ({ OpenForSelection: 'Selection open', Closed: 'Selection closed', Published: 'Published', Archived: 'Archived', Draft: 'Draft' } as Record<ScheduleStatus, string>)[status] }
function lifecycleHelp(status: ScheduleStatus) { return ({ OpenForSelection: 'Resident Assistants can claim open shifts.', Closed: 'Review coverage and distribution before publishing.', Published: 'The final schedule is available for PDF export.', Archived: 'Historical record; no further changes are allowed.', Draft: 'Only Hall Directors can view this schedule.' } as Record<ScheduleStatus, string>)[status] }
function initials(name: string) { return name.split(' ').map((part) => part[0]).slice(0, 2).join('') }
function readableAction(action: string) { return action.toLowerCase().replaceAll('_', ' ') }
function summaryJson(before?: string, after?: string) { try { return `Before\n${before ? JSON.stringify(JSON.parse(before), null, 2) : '—'}\n\nAfter\n${after ? JSON.stringify(JSON.parse(after), null, 2) : '—'}` } catch { return 'Change details unavailable.' } }
function roleLabel(role: 'ResidentAssistant' | 'HallDirector' | 'Admin') { return role === 'Admin' ? 'Administrator' : role === 'HallDirector' ? 'Hall Director' : 'Resident Assistant' }
function roleOptions(actorRole: HallRole): HallRole[] { return actorRole === 'Admin' ? ['ResidentAssistant', 'HallDirector', 'Admin'] : ['ResidentAssistant'] }
