services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: raduty-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Local_RaDuty_123!"
    ports:
      - "1433:1433"
    volumes:
      - raduty-sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Local_RaDuty_123!' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  raduty-sql-data:

